# Generated by Django 3.1.2 on 2020-10-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_auto_20201020_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='likes',
        ),
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.BooleanField(null=True),
        ),
    ]
