# Generated by Django 3.1.2 on 2020-10-20 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_auto_20201021_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='likes',
        ),
    ]
