# Generated by Django 3.1.2 on 2020-10-20 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0005_remove_profile_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
