# Generated by Django 3.1.2 on 2020-10-24 14:19

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0009_remove_profile_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='post',
            field=tinymce.models.HTMLField(default=0),
            preserve_default=False,
        ),
    ]
